### ISSUE TITLE
Conference Final ToDo List

### ISSUE THREAD

**Issue by rustyb** [rustyb/entsoe_conf#1]
List of remaining tasks to be completed:

- [x] Homepage: I think we should mark (TBC) near the names of speakers who are not confirmed
- [x] Homepage, ‘Agenda’: one sentence is missing , in red below
 
A New Deal for the EU post-recession? What should it be based upon? What is the role of the resilient
Energy Union? Commission President Juncker’s 10 ambitious priorities focus on better regulation and on
large scale public-private investments into innovation and infrastructure across the EU. What can be
achieved until 2019, the end of the mandate of the current Commission?

- [x] Homepage: Date on the top left, no th
- [x] Programme: date is wrong
- [x] Register: I’d rather have 3 points: EU Institutions and permanent representations ; media ; ENTSO-E members
- [x] Register: date of end registration should be 15 November? We can update later, it depends of how many people we have and of the badges supplier
- [ ] Speakers: here also we should specify when they are tbc
- [x] Speakers: the i is missing in ‘Gogolewski’
- [x] Venue: there is a typo in the first line

-------

- [ ] The homepage texts and pics might need to be looked at again. The agenda is not really clear, Why are talking 2019 (suppose end of the mandate of the EC but that should be stated somewhere)
- [x] The list of speakers states Frauke Thies in her former roke
- [x] Peder’s pic is worh changing. The old one we were using was better I think
- [ ] The Schedule intro is interesting but a bit repetitive just stick to the second sentence
- [x] Not all speakers have pics in the programme
- [x] The colour code of the dots is not really clear to me. Think it is a good idea but then shoul be explained what colour corresponds to what.
- [x] The text in bracket on the session on sec of supply is a bit long compared to the other panels
- [ ] Edwin told me RSCIs might have to change names and be called RCC Regional Coordination Centres to reflect the fact that their missions will be broader than security. Will ask JB to check with SOC
- [x] Do we spell out dates like November 14th or 14 November?
- [x] Did not we decide on a # for the conference that we could add (think Colin suggested #entsoe2015
- [ ] Maybe rather than text, we should ask Konni or Peder to record a video address to welcome participants to the conference
- [x] On registration, how do people who do not have to pay register? I only see button for paying registration
- [x] Should not we ask on registration form, organisation and position?
- [x] On top of reg page I would take off Brussels after Annual Conference
- [x] I would put the email address for the conference in the footer of each page as well as the # if we decide to use one
- [x] Should not we have Partner or Sponsors page to give them some visibility and ideally get a quote from their top man/ woman on why they decided to partner with ENTSO-E?
- [x] There is born to be questions about hotels. Should we add in the registration page a note saying that ENTSO-E has not done nay pre-booking and that part pants are expected to sort out their accommodation. ENTSO-E does not recommend any hotel in particular.

**Comment by rustyb** [comment]
Will delete colour coded dots.....
